name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Go
        uses: actions/setup-go@f91f14f88a7066d33fac3583e743a121503ef259 # v5.3.0
        with:
          go-version: '1.26.3'
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@2226d7dc0643ea153a846f414e27f053594b2a3c # v6.4.3
        with:
          version: v2.12

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Go
        uses: actions/setup-go@f91f14f88a7066d33fac3583e743a121503ef259 # v5.3.0
        with:
          go-version: '1.26.3'
          cache: true
      - name: Install dependencies
        run: go mod download
      - name: Check formatting
        run: x=$(gofmt -l .); if [ -n "$x" ]; then echo "Following files are not formatted:"; echo "$x"; exit 1; fi
      - name: Go Vet
        run: go vet ./...
      - name: Build
        run: go build -v -o /dev/null ./main.go
      - name: Run tests
        run: go test -v ./...
